version: '3'

services:
  client:
    container_name: "Pokemon-Client"
    build: ./client/
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    tty: true
    networks:
      - Pokemon-SPA
  api:
    container_name: "Pokemon-Api"
    build: ./api/
    volumes:
      - ./api:/usr/src/app
    ports:
      - "3001:3001"
    tty: true
    networks:
      - Pokemon-SPA
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokeapi
    volumes:
      - ./db:/var/lib/postgresql/data/
    networks:
      - Pokemon-SPA

networks:
  Pokemon-SPA:
